language: java
sudo: false

jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
install: true

script:
  - travis_wait 30 mvn clean package -Dmaven.skip=true

after_success:
  - echo mvn package success
  - bash <(curl -s https://codecov.io/bash) # 编译通过后启用codecov