language: java
sudo: false

jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
install: true

#deploy:
#  provider: script
#  script: travis_wait 30 mvn clean package -DskipTests=false -Dcheckstyle.skip=false
#  on:
#    branch: master
before_deploy:
  - echo maven runing

script:
  - travis_wait 30 mvn clean package -DskipTests=false -Dcheckstyle.skip=false

after_success:
  - echo mvn package success
  - bash <(curl -s https://codecov.io/bash) # 编译通过后启用codecov